name: parse_server_sdk
description: This is a Flutter plugin that allows communication with a Parse Server, (https://parseplatform.org)
version: 1.0.0
homepage: https://github.com/phillwiggins/flutter_parse_sdk
author: PhillWiggins <phill.wiggins@gmail.com>

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  # Networking
  web_socket_channel: ^1.0.9
  http: ^0.12.0

  # Utils
  intl: ^0.15.7